export const ANSI_RESET = "\x1b[0m"
export const ANSI_BRIGHT = "\x1b[1m"
export const ANSI_DIM = "\x1b[2m"
export const ANSI_UNDERSCORE = "\x1b[4m"
export const ANSI_BLINK = "\x1b[5m"
export const ANSI_REVERSE = "\x1b[7m"
export const ANSI_HIDDEN = "\x1b[8m"

export const ANSI_FG_BLACK = "\x1b[30m"
export const ANSI_FG_RED = "\x1b[31m"
export const ANSI_FG_GREEN = "\x1b[32m"
export const ANSI_FG_YELLOW = "\x1b[33m"
export const ANSI_FG_BLUE = "\x1b[34m"
export const ANSI_FG_MAGENTA = "\x1b[35m"
export const ANSI_FG_CYAN = "\x1b[36m"
export const ANSI_FG_WHITE = "\x1b[37m"

export const ANSI_BG_BLACK = "\x1b[40m"
export const ANSI_BG_RED = "\x1b[41m"
export const ANSI_BG_GREEN = "\x1b[42m"
export const ANSI_BG_YELLOW = "\x1b[43m"
export const ANSI_BG_BLUE = "\x1b[44m"
export const ANSI_BG_MAGENTA = "\x1b[45m"
export const ANSI_BG_CYAN = "\x1b[46m"
export const ANSI_BG_WHITE = "\x1b[47m"